BIND_IP=${BIND_IP:-0.0.0.0}
BIND_PORT=${BIND_PORT:-0}
ROUTER_HOST=${ROUTER_HOST:-router.csrb.app}
ROUTER_PORT=${ROUTER_PORT:-32450}
ROUTER_INTERSPACE_USEC=${ROUTER_INTERSPACE_USEC:-100}

COMMAND_TIMEOUT=2000
COMMAND_TIMEOUT_RETRIES=3

OS=`uname -s`
case "${OS}" in
	Linux)		MD5SUM=md5sum ;;
	OpenBSD)	MD5SUM=md5 ;;
	FreeBSD)	MD5SUM=md5 ;;
	NetBSD)		MD5SUM=md5 ;;
esac

NODEID_HOSTNAME=${HOSTNAME:-`hostname -s`}
NODEID_OF_HOSTNAME=`echo -n ${NODEID_HOSTNAME} | tr -d '\n' | ${MD5SUM} | cut -d ' ' -f 1 | tr '[:lower:]' '[:upper:]'`
NODEID=$(printf "%032s" "${NODEID:-$NODEID_OF_HOSTNAME}")

__SCRIPTS_DIR=$(dirname $(readlink -f $0))

CA_CERT=${CA_CERT:-${__SCRIPTS_DIR}/../CERTS/CA.nodes.csrb.crt}
NODE_CERT=${NODE_CERT:-${__SCRIPTS_DIR}/../CERTS/C9BAD58F23D5A6C095C0571512CD318D.nodes.csrb.pem}
STORAGE_PATH=${STORAGE_PATH:-~/CSRBSTORAGE/${NODEID}/}

